name: Build Application

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*' # Triggers on v1.0, v2.0-beta, etc.
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.13.9'
            cache: 'pip'

        - name: Install Dependencies
          run: |
            pip install -r requirements.txt
            pip install pyinstaller

        # --- WINDOWS BUILD STEP ---
        - name: Build with PyInstaller (Windows)
          if: runner.os == 'Windows'
          run: |
            pyinstaller --noconfirm --onedir --windowed --name "T1MESCULPTURES" --icon="assets/app/icon.ico" --add-data "assets/app/icon.ico;assets/app" --collect-all sv_ttk --collect-all pyvista --hidden-import="PIL" --hidden-import="cv2" algorithm/code/app/app.py

        # --- MAC BUILD STEP ---
        - name: Build with PyInstaller (macOS)
          if: runner.os == 'macOS'
          run: |
            pyinstaller --noconfirm --onedir --windowed --name "T1MESCULPTURES" --icon="assets/app/icon.icns" --add-data "assets/app/icon.icns:assets/app" --collect-all sv_ttk --collect-all pyvista --hidden-import="PIL" --hidden-import="cv2" algorithm/code/app/app.py

        # --- UPLOAD ARTIFACTS (UPDATED TO V4) ---
        - name: Upload Build Artifact
          uses: actions/upload-artifact@v4
          with:
            name: T1MESCULPTURES-${{ runner.os }}
            path: dist/T1MESCULPTURES*
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') # Only run this if a tag was pushed!
    
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: T1MESCULPTURES-Windows
          path: ./windows-build

      - name: Download Mac Artifact
        uses: actions/download-artifact@v4
        with:
          name: T1MESCULPTURES-macOS
          path: ./mac-build

      - name: Zip Artifacts for Release
        run: |
          # Zip them up nicely so users download 1 file per OS
          cd windows-build && zip -r ../T1mesculptures-Windows.zip ./* && cd ..
          cd mac-build && zip -r ../T1mesculptures-macOS.zip ./* && cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            T1mesculptures-Windows.zip
            T1mesculptures-macOS.zip
          draft: false
          prerelease: false
          generate_release_notes: true