name: Build Application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
            cache: 'pip'

        - name: Install Dependencies
          run: |
            pip install -r requirements.txt
            pip install pyinstaller

        # --- WINDOWS BUILD STEP ---
        - name: Build with PyInstaller (Windows)
          if: runner.os == 'Windows'
          run: |
            pyinstaller --noconfirm --onedir --windowed --name "T1MESCULPTURES" --icon="assets/app/icon.ico" --collect-all sv_ttk --collect-all pyvista --hidden-import="PIL" --hidden-import="cv2" algorithm/code/app/app.py

        # --- MAC BUILD STEP ---
        - name: Build with PyInstaller (macOS)
          if: runner.os == 'macOS'
          run: |
            pyinstaller --noconfirm --onedir --windowed --name "T1MESCULPTURES" --icon="assets/app/icon.icns" --collect-all sv_ttk --collect-all pyvista --hidden-import="PIL" --hidden-import="cv2" algorithm/code/app/app.py

        # --- UPLOAD ARTIFACTS (UPDATED TO V4) ---
        - name: Upload Build Artifact
          uses: actions/upload-artifact@v4
          with:
            name: T1MESCULPTURES-${{ runner.os }}
            path: dist/T1MESCULPTURES*